### ISSUE TITLE
Allow multi-publishers in a topic

### ISSUE THREAD

**Issue by pedrocunha** [HouseTrip/routemaster#41]
The current logic of Routemaster only allows to publish in a topic the initial publisher: https://github.com/HouseTrip/routemaster/blob/master/routemaster/models/topic.rb#L25-L28. 

What are the consequences of changing this behaviour ? What about the rest of the codebase ?

What would be the most graceful API to allow multiple publishers ? 

ENV variable stating: 
a) which clients can publish ?
b) which topics can be multi-published and by who ?
c) others... 

/cc @mezis

**Comment by mezis** [comment]
The logic is one of domain design — only one "service" should be authoritative for the state of a topic / domain concept / class of resources, therefore only one service should be able to publish events regarding a given topic.

I think the need for multiple publishers for a single topic smells of concern spill, although of course I don't know the exact situation.

If you _really_ want to allow this, I'd make it possible but hard.

> What would be the most graceful API to allow multiple publishers

I'd leave the default be: the first to publish becomes the "default" publisher for a topic.

Besides I'd support (as per your suggestion) an environment variable — e.g. `ROUTEMASTER_UNSAFE_GOD_PUBLISHERS=<comma-separated client ids>`, checked from [models/topic.rb](https://github.com/HouseTrip/routemaster/blob/master/routemaster/models/topic.rb#L25-L28)


> What are the consequences of changing this behaviour ? What about the rest of the codebase ?

None if done as above. The god publisher(s) wouldn't "officially" be publishers at all, and wouldn't appear in the monitoring responses for instance.

**Comment by pedrocunha** [comment]
Thanks for the very detailed explanation. I think in theory what you are saying is completely correct.

This need arises by the app `routemaster-timemachine` which would like to be able to re-publish in a topic a past message. The infrastructure already supports setting up timestamps in past but now I've hit this road block and I wonder what would be the consequences of changing this behaviour.

I think the publisher default logic should stand as well since it's very handy to not be declarative/configurative all the time.

I like this idea:
> None if done as above. The god publisher(s) wouldn't "officially" be publishers at all, and wouldn't appear in the monitoring responses for instance.

This could mean that `routemaster-timemachine` is impersonating other publishers which in a way is what we want (same body message, same origin). I wonder how we could for a safe-side, keep a log of it though for debug purposes. Maybe a log in the `routemaster-timemachine` app would suffice.

**Comment by mezis** [comment]
Sounds good. Another way to do this would be for `routemaster-timemachine` to record the UUID of the publisher with the events (using the `GET /topics` monitoring endpoint), and when replaying, authenticate with that UUID.

That way you wouldn't even need to change `routemaster` at all?

**Comment by pedrocunha** [comment]
Hmm that's an interesting approach, less intrusive. Interesting how easily you can bypass and impersonate an authority in Routemaster domain. 

I think I don't need to change `routemaster` at all but I have to change `routemaster-client` since it does not implement yet `#monitor_topics`.
