### ISSUE TITLE
Rescuing timeouts when delivering to subscribers

### ISSUE THREAD

**Issue by mrship** [HouseTrip/routemaster#53]
As far as I can tell, should posting a new topic event to a subscriber fail due to a time out, Faraday will throw an error that won't get caught. 

```
    # send data
    response = _conn.post do |post|
      post.headers['Content-Type'] = 'application/json'
      post.body = data.to_json
    end

    if response.success?
      _log.debug { "delivered #{@buffer.length} events to '#{@subscription.subscriber}'" }
      return true
    end

    _log.warn { "failed to deliver #{@buffer.length} events to '#{@subscription.subscriber}'" }
    raise CantDeliver.new('delivery failure')
```

I guess at this point that the message won't get ack'd, so it will ultimately be retried, but would it be better to rescue the Faraday error rather than let it raise?

//cc @mezis @pedrocunha

**Comment by mezis** [comment]
Do you mean that in the event of a timeout, `_conn.post` will raise instead of returning?

**Comment by mrship** [comment]
Yes, exactly.

**Comment by mezis** [comment]
Then yes, I'd capture those exceptions in the code above.
